### ISSUE TITLE
Still mantained

### ISSUE THREAD

**Issue by 0plus1** [tpavlek/oauth2-twitch#5]
Dear @tpavlek ,

I forked your integration and changed quite a bit to make it work with the latest version of the league package. I also removed the Laravel integration as I consider it out of the scope of this package.

Should I bother with a pull request or should I just take over the package? I am currently managing a twitch integration and I am in constant need to update the package, that is the reason why I took ownership of the package in the json file.

Here is my fork: https://github.com/0plus1/oauth2-twitch

Thanks for your time

Regards,

Davide

**Comment by tpavlek** [comment]
Thanks for this!

I actually saw your work the other day and was going to reach out for a pull, since it seemed like good work. The site that I maintained with Twitch integration is now defunct, which is why this package didn't keep up. That said, I'd rather not have outdated packages that don't work.

Going forward, there's a couple options: 
1. You can make pulls as necessary. I'm usually quite responsive to pulls and merge them quickly.
2. I can add you as a maintainer to my repo and you can make commits directly - normally that's not something I do, but I've seen the work on your fork and it's definitely good quality! :+1: 
3. I can deprecate my package and point to you.

I'm fine with all three options, so let me know what works best for you :)

**Comment by tpavlek** [comment]
I've merged your pull and added you as a collaborator.

If you need any help with anything feel free to reach out via email: troy@tpavlek.me
